name: Package build
on: push
jobs:
  test_package:
    runs-on: package-builder
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Test package
      run: |
        npm install
        npm run test
  build_package:
    runs-on: package-builder
    environment: Production
    needs: test_package
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: |
        npm install
        npm run build
  deploy_package:
    runs-on: container-builder
    environment: Production
    needs: build_package
    steps:
    - uses: actions/checkout@v4
    - name: Deploy container image
      run: |
        npm config set //${{ vars.NPM_REGISTRY }}/:_authToken ${{ secrets.NPM_TOKEN }}
        {
          npm publish --access public && npm config delete //${{ vars.NPM_REGISTRY }}/:_authToken
        } || {
          npm config delete //${{ vars.NPM_REGISTRY }}/:_authToken
          exit 1
        }